import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const pwd=process.cwd();
async function start(t,scenario,existing){const dir=existing||await mkdtemp(join(tmpdir(),'portal-test-'));const env={...process.env,PORT:'0',HOST:'127.0.0.1',DATA_DIR:dir,FS_MODE:scenario?'test':'simulation',CUSTOMER_USERNAME:'buyer',CUSTOMER_PASSWORD:'CustomerTest123!',ADMIN_USERNAME:'admin',ADMIN_PASSWORD:'AdminTest12345!',FS_API_USERNAME:'test-user',FS_API_PASSWORD:'fake-test-key',FS_SUBSCRIPTION_ID:'test-sub',FS_ACCOUNT_ID:'test-account',MOCK_LOG:join(dir,'requests'),MOCK_SCENARIO:scenario||''};const child=spawn(process.execPath,[...(scenario?['--import',join(pwd,'tests/fs-mock.mjs')]:[]),'server/index.mjs'],{cwd:pwd,env,stdio:['ignore','pipe','pipe']});let errors='';child.stderr.on('data',d=>errors+=d);const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout '+errors)),10000);child.stdout.on('data',d=>{const m=String(d).match(/http:\/\/127.0.0.1:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});child.on('exit',()=>{clearTimeout(timer);reject(Error(errors));});});
let cookie='';const call=async(body,path='/api/portal',origin=base)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{cookie,Origin:origin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};};const login=role=>call({action:'login',role,username:role==='admin'?'admin':'buyer',password:role==='admin'?'AdminTest12345!':'CustomerTest123!'});const stop=()=>new Promise(resolve=>{if(child.exitCode!==null)return resolve();child.once('exit',resolve);child.kill();});t.after(async()=>{await stop();if(!existing)await rm(dir,{recursive:true,force:true});});return {base,call,login,stop,dir,log:async()=>{try{return (await readFile(join(dir,'requests'),'utf8')).trim().split('\n').map(JSON.parse);}catch{return [];}}};}
const cancel={action:'cancel',reasonId:'1',feedbackText:'Test feedback',billingPeriod:1,confirm:true};
test('simulation auth, CSRF, role separation, both timing choices, and persistent survey',async t=>{const s=await start(t);assert.equal((await s.call()).status,401);assert.equal((await s.login('customer')).status,200);assert.equal((await s.call(null,'/api/admin')).status,403);assert.equal((await s.call(cancel,'/api/portal','https://evil.example')).status,403);assert.equal((await s.call({...cancel,confirm:false})).status,400);assert.equal((await s.call(cancel)).status,200);assert.equal((await s.call()).data.subscription.state,'canceled');await s.call({action:'reset'});assert.equal((await s.call({...cancel,billingPeriod:0})).status,200);assert.equal((await s.call()).data.subscription.state,'deactivated');await s.login('admin');assert.equal((await s.call(null,'/api/admin')).data.rows.length,2);assert.equal((await s.call(cancel)).status,403);await s.stop();const restarted=await start(t,null,s.dir);await restarted.login('admin');assert.equal((await restarted.call(null,'/api/admin')).data.rows.length,2);});
for(const period of [0,1])test('FastSpring test payload and order billingPeriod='+period,async t=>{const s=await start(t,'ok');await s.login('customer');assert.equal((await s.call({...cancel,billingPeriod:period})).status,200);const writes=(await s.log()).filter(r=>r.method!=='GET');assert.equal(writes.length,2);assert.deepEqual(writes[0].body,{subscription:'test-sub',cancelSurvey:{reasonId:'1',feedbackText:'Test feedback',lang:'en'}});assert.equal(writes[1].method,'DELETE');assert.equal(writes[1].query,'?billingPeriod='+period);await s.call(cancel);assert.equal((await s.log()).filter(r=>r.method==='DELETE').length,1);await s.login('admin');const admin=(await s.call(null,'/api/admin')).data;assert.equal(admin.rows[0].status,'complete');assert.equal(admin.remote.cancelSurvey.reasonId,'1');});
for(const scenario of ['live','wrong-owner'])test('blocks '+scenario+' before mutation',async t=>{const s=await start(t,scenario);await s.login('customer');assert.equal((await s.call(cancel)).status,409);assert.equal((await s.log()).filter(r=>r.method!=='GET').length,0);});
test('survey failure blocks cancellation and can retry',async t=>{const s=await start(t,'survey-failure');await s.login('customer');assert.equal((await s.call(cancel)).status,502);assert.equal((await s.log()).filter(r=>r.method==='DELETE').length,0);assert.equal((await s.call(cancel)).status,200);await s.login('admin');const rows=(await s.call(null,'/api/admin')).data.rows;assert.equal(rows.length,1);assert.equal(rows[0].status,'complete');});
test('unknown cancel result blocks automatic retry',async t=>{const s=await start(t,'cancel-unknown');await s.login('customer');assert.equal((await s.call(cancel)).status,502);assert.equal((await s.call(cancel)).status,409);assert.equal((await s.log()).filter(r=>r.method==='DELETE').length,1);});
test('HTTP 200 with cancellation error is not reported as success',async t=>{const s=await start(t,'body-error');await s.login('customer');assert.equal((await s.call(cancel)).status,502);await s.login('admin');assert.equal((await s.call(null,'/api/admin')).data.rows[0].status,'cancel_requested');});
test('new customer login cannot bypass unknown outcome guard',async t=>{const s=await start(t,'cancel-unknown');await s.login('customer');await s.call(cancel);await s.login('customer');assert.equal((await s.call(cancel)).status,409);assert.equal((await s.log()).filter(r=>r.method==='DELETE').length,1);});
